Platform-HackerRank 
Concept: LENGTH, ORDER BY, LIMIT

QUERY
SELECT CITY,LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) ASC ,CITY ASC LIMIT 1;

SELECT CITY,LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC ,CITY ASC LIMIT 1;